### ISSUE TITLE
Custom config.txt parameters

### ISSUE THREAD

**Issue by jakymiwm** [PiNet/PiNet-Boot#2]
You can support custom config.txt parameters by using the PI SN. 
On: https://www.raspberrypi.org/documentation/configuration/config-txt.md
Under: "THE SERIAL NUMBER FILTER"

[0x12345678]
"# settings here are applied only to the Pi with this serial"
[all]
"# settings here are applied to all hardware"

**Comment by gbaman** [comment]
Pleased to confirm this is now supported on PiNet Jessie https://github.com/PiNet/PiNet/issues/54
